---
development:
  cloud_name: dklf0amce
  api_key: '475992557829252'
  api_secret: o2NvpjdWehv02mWm5Gk8y_ZJClI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dklf0amce
  api_key: '475992557829252'
  api_secret: o2NvpjdWehv02mWm5Gk8y_ZJClI
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dklf0amce
  api_key: '475992557829252'
  api_secret: o2NvpjdWehv02mWm5Gk8y_ZJClI
  enhance_image_tag: true
  static_image_support: false
