# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cabd14d479e07841d1677883069716aeae3c8db4c64df895b5935c06ce6326452cd900f151b0d42144707c64c8db423703e4930f85fedeac02987785c7a143b

test:
  secret_key_base: ca43e12a696a67c124b4fbef0c44d04f6716b6b74f73042011a5572b3bce78fccbdafbe06f8e89a07af8c0b9b08357902fe00dfff66ae0a8f4d3d60cbfdc6f0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
